// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56BbVMvbMdds7Mt3cFtxeG8iqi5-UwEE',
    appId: '1:613180324118:web:7cc42b8133f05bfd75b837',
    messagingSenderId: '613180324118',
    projectId: 'lifelist-439718',
    authDomain: 'lifelist-439718.firebaseapp.com',
    storageBucket: 'lifelist-439718.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtF7P14CaJDe78BK7sVpdd0oNq-npkDc',
    appId: '1:613180324118:android:d35c523e75641bc075b837',
    messagingSenderId: '613180324118',
    projectId: 'lifelist-439718',
    storageBucket: 'lifelist-439718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2-vSXdLO8krcvDaOBLYgBiHS153_KA0',
    appId: '1:613180324118:ios:0d3235c2f0ff97a375b837',
    messagingSenderId: '613180324118',
    projectId: 'lifelist-439718',
    storageBucket: 'lifelist-439718.appspot.com',
    iosClientId: '613180324118-5g111gmins25907u6ep9lk9chfup8929.apps.googleusercontent.com',
    iosBundleId: 'com.example.vidyoo',
  );

}